version: '3'
services:
  app:
    container_name: app
    build: .
    restart: always
    volumes:
      - ./:/var/www/
    entrypoint: dockerize -template ./.docker/app/.env.testing:.env.testing -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/app/entrypoint.sh
    environment:
      - _DB_HOST=db
      - _DB_DATABASE=code_micro_videos
      - _DB_USERNAME=root
      - _DB_PASSWORD=root
      - _TEST_DB_DATABASE=code_micro_videos_tests
    depends_on:
      - db
      - redis
    networks:
      - network-app

  db:
    image: mysql:5.7
    restart: always
    command: --innodb-use-native-aio=0
    container_name: db
    tty:  true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=code_micro_videos
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
    - "./.docker/dbdata:/var/lib/mysql"
    - "./.docker/mysql:/docker-entrypoint-initdb.d"
    networks:
      - network-app

  nginx:
    build: ./.docker/nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    environment:
      - PHP_FPM_HOST=app
      - PHP_FPM_PORT=9000
    volumes:
      - ./:/var/www
    entrypoint: dockerize -template /var/www/.docker/nginx/nginx.tmpl:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off;"
    networks:
      - network-app
    depends_on:
      - app
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - network-app
networks:
  network-app:
    driver: bridge
